# Generated by Django 6.0.1 on 2026-01-15 21:26

import finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
                ('objects', finance.models.UtilisateurManager()),
            ],
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Initial Balance'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Last Name'),
        ),
    ]
