# Generated by Django 6.0.1 on 2026-01-16 22:47

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_compte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('type_transaction', models.CharField(choices=[('REVENU', 'Revenu'), ('DEPENSE', 'Dépense'), ('ECHEC', 'Épargne')], default='DEPENSE', max_length=10, verbose_name='Type de transaction')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (CFA)')),
                ('compte', models.CharField(choices=[('Especes', 'Especes'), ('momo', 'MoMo'), ('orange', 'Orange Money'), ('banque', 'Épargne bancaire')], max_length=20, verbose_name='Compte')),
                ('categorie', models.CharField(choices=[('nourriture', 'Alimentation & Restaurants'), ('transport', 'Transport'), ('shopping', 'Shopping'), ('loisirs', 'Loisirs & Divertissement'), ('factures', 'Factures & Services'), ('sante', 'Santé'), ('education', 'Éducation'), ('autre', 'Autre')], max_length=50, verbose_name='Catégorie')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date'],
            },
        ),
    ]
